# Generated by Django 4.1.7 on 2023-04-03 21:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='media',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='media',
        ),
        migrations.RemoveField(
            model_name='step',
            name='order',
        ),
        migrations.AddField(
            model_name='recipe',
            name='av_rating',
            field=models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=2),
        ),
        migrations.AddField(
            model_name='recipe',
            name='base_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_recipe', to='recipe.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='num_rated',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_rating',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='step',
            name='time_taken',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='vid',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serve',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='RecipeMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='')),
                ('thumbnail', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_media', to='recipe.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('media', models.FileField(blank=True, upload_to='')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
            ],
        ),
    ]
