# Generated by Django 4.1.7 on 2023-04-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipeingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='base_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='serving_amount',
        ),
    ]
