# Generated by Django 4.1.7 on 2023-04-10 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('av_rating', models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=2)),
                ('total_rating', models.PositiveIntegerField(default=0, editable=False)),
                ('num_rated', models.PositiveIntegerField(default=0, editable=False)),
                ('likes', models.PositiveIntegerField(default=0, editable=False)),
                ('main_vid', models.FileField(blank=True, null=True, upload_to='main_vid/')),
                ('main_img', models.ImageField(blank=True, null=True, upload_to='main_img/')),
                ('prep_time', models.PositiveIntegerField()),
                ('cook_time', models.PositiveIntegerField()),
                ('total_time', models.PositiveIntegerField()),
                ('diets', models.CharField(max_length=50)),
                ('cuisine', models.CharField(max_length=50)),
                ('servings', models.PositiveIntegerField(default=1, editable=False)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='owned_recipes', to=settings.AUTH_USER_MODEL)),
                ('base_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_recipe', to='RecipeDetails.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.FileField(blank=True, null=True, upload_to='step_vid/')),
                ('img', models.ImageField(blank=True, null=True, upload_to='step_img/')),
                ('number', models.CharField(max_length=2)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('time_taken', models.PositiveIntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='RecipeDetails.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('serving_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('measuring_unit', models.CharField(max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipeIngredients', to='RecipeDetails.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='RecipeDetails.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100)),
                ('commenter', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='posted_comments', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_comments', to='RecipeDetails.recipe')),
            ],
        ),
    ]
