# Generated by Django 4.1.7 on 2023-04-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_profile_last_touched_profile_shopping_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avi',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars'),
        ),
    ]
